const PLANTAS = [

  // ─── INTERIOR ───────────────────────────────────────
  {
    id: 1,
    nombre: "Potus",
    cientifico: "Epipremnum aureum",
    emoji: "🌿",
    categoria: "interior",
    diasRiego: 6,
    luz: "Sol indirecto",
    mesesSiembra: "Todo el año",
    dificultad: "Fácil",
    descripcion: "Una de las plantas de interior más populares del mundo. Extremadamente resistente, tolera el descuido y purifica el aire. Ideal para principiantes. Sus hojas verde brillante con manchas amarillas la hacen muy decorativa.",
    cuidados: "Regá cuando la capa superior de tierra esté seca. Evitá el sol directo que puede quemar sus hojas. Tolera poca luz pero crece mejor con luz indirecta. Podés reproducirla cortando tallos y poniéndolos en agua.",
    curiosidad: "La NASA la incluye en su lista de plantas purificadoras del aire, capaz de eliminar tóxicos como el formaldehído.",
    tags: ["interior", "fácil"]
  },
  {
    id: 2,
    nombre: "Helecho de Boston",
    cientifico: "Nephrolepis exaltata",
    emoji: "🪴",
    categoria: "interior",
    diasRiego: 2,
    luz: "Sol indirecto",
    mesesSiembra: "Todo el año",
    dificultad: "Media",
    descripcion: "Elegante planta de interior con hojas largas y arqueadas de color verde intenso. Ideal para colgar o colocar en superficies altas donde sus hojas puedan caer libremente.",
    cuidados: "Necesita humedad constante, tanto en la tierra como en el ambiente. Rociá las hojas con agua cada 2-3 días. Alejala de fuentes de calor y corrientes de aire frío.",
    curiosidad: "Los helechos son plantas muy antiguas: existen desde hace más de 360 millones de años, antes que los dinosaurios.",
    tags: ["interior", "decorativa"]
  },
  {
    id: 3,
    nombre: "Higuera hoja de violín",
    cientifico: "Ficus lyrata",
    emoji: "🌿",
    categoria: "interior",
    diasRiego: 5,
    luz: "Sol indirecto",
    mesesSiembra: "Todo el año",
    dificultad: "Media",
    descripcion: "Planta popular de interior tropical apreciada por sus hojas enormes, cerosas y brillantes en forma de lira (o violín), que pueden superar los 25-50 cm.",
    cuidados: "Requiere mucha luz indirecta, riegos moderados, y un ambiente con alta humedad.",
    curiosidad: "La Ficus lyrata es una planta tropical nativa de África Occidental famosa por sus grandes hojas brillantes en forma de lira. En la naturaleza puede superar los 15-20 metros, pero en interiores se mantiene como planta escultural.",
    tags: ["interior", "decorativa"]
  },
  {
   id: 4,
    nombre: "Monstera",
    cientifico: "Monstera Deliciosa",
    emoji: "🌿",
    categoria: "interior",
    diasRiego: 5,
    luz: "Sol indirecto",
    mesesSiembra: "Todo el año",
    dificultad: "Fácil",
    descripcion: "Es una planta trepadora tropical famosa por sus grandes hojas verde oscuro brillante, acorazonadas y con cortes o agujeros naturales.",
    cuidados: "Es una planta resistente que requiere luz indirecta, riego moderado y alta humedad ambiental.",
    curiosidad: "La Monstera deliciosa produce un fruto comestible, conocido como piñanona, que sabe a una mezcla de piña, mango y banana. Sin embargo, solo es seguro comerlo cuando está totalmente maduro.",
    tags: ["interior", "fácil"]
  },
  // ─── HUERTA ───────────────────────────────────────
  { 
    id: 5,
    nombre: "Tomate",
    cientifico:"Solanum Lycopersicum",
    emoji:"🍅",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol directo",
    mesesSiembra:"Primavera",
    dificultad:"Media",
    descripcion: "Planta muy cultivada que produce frutos jugosos, usados en muchas comidas. Crece bastante y necesita soporte para sostener sus tallos.",
    cuidados: "Colocar soporte para que crezca recta y usar suelo bien drenado. Regar sin encharcar y podar algunos brotes para mejorar la producción.",
    curiosidad: " Aunque parece verdura, el tomate es una fruta porque tiene semillas. ",
    tags:["huerta", "fruto"]

  },
  {
    id: 6,
    nombre: "Lechuga",
    cientifico:"Lactuca sativa",
    emoji:"🥬",
    categoria:"huerta",
    diasRiego:1,
    luz:"Sol o semisombra",
    mesesSiembra:"Todo el año",
    dificultad:"Fácil",
    descripcion: "Es una planta de huerta muy popular cultivada por sus hojas comestibles, ideales para ensaladas. Tiene hojas grandes, suaves o rizadas, con alto contenido de agua (aprox. 95%) y muy bajas calorías. Crece rápidamente y existen muchas variedades que se adaptan a distintos climas.",
    cuidados: "Mantener el suelo húmedo sin exceso de agua. Evitar el calor fuerte porque puede amargarse.",
    curiosidad: "La lechuga era cultivada por egipcios y romanos desde hace miles de años.",
    tags:["huerta", "fácil"],
  },
  {
    id:7,
    nombre: "Albahaca",
    cientifico:"Ocimum basilicum",
    emoji:"🌿",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol directo",
    mesesSiembra:"Primavera",
    dificultad:"Fácil",
    descripcion: "Planta muy conocida por su intenso aroma y sabor característico. Se utiliza en una gran variedad de platos, especialmente en la cocina italiana. Es ideal para cultivar en macetas o pequeños espacios.",
    cuidados: "Se recomienda podar sus hojas con frecuencia para estimular su crecimiento. Necesita buena luz solar y evitar el exceso de agua en las raíces. También es importante protegerla del frío.",
    curiosidad: "La albahaca no solo sirve para cocinar, también ayuda a ahuyentar insectos como mosquitos, por lo que es útil tenerla cerca de otras plantas.",
    tags:["huerta", "aromática"],
  },
  
     {
    id:8,
    nombre: "Pimiento",
    cientifico:" Capsicum annuum",
    emoji:"🌶️ ",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol directo",
    mesesSiembra:"Agosto o Octubre",
    dificultad:"Media",
    descripcion: " Planta que produce frutos de diferentes colores como rojo, verde y amarillo. Son muy utilizados en la cocina por su sabor dulce o ligeramente picante. Necesita calor y tiempo para desarrollarse correctamente.",
    cuidados: "Requiere temperaturas cálidas y protección frente al frío o heladas. Es importante mantener un riego regular y un suelo fértil. En algunos casos, puede necesitar soporte para sostener los frutos.",
    curiosidad: "Los pimientos contienen más vitamina C que muchas frutas cítricas, por lo que son muy beneficiosos para la salud.",
    tags:["huerta", "saludable"],
  },
  {
    id:9,
    nombre: " Zanahoria",
    cientifico:"Daucus carota",
    emoji:"🥕 ",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol directo",
    mesesSiembra:"Otoño o invierno",
    dificultad:"Media",
    descripcion: "  Planta cuya parte comestible es una raíz de color naranja que crece bajo tierra. Es muy nutritiva y se consume tanto cruda como cocida en distintas preparaciones. Su forma depende mucho de la calidad del suelo.",
    cuidados: "Necesita suelos sueltos, profundos y sin piedras para crecer recta. El riego debe ser regular para evitar que se agriete. Es importante no compactar la tierra durante su crecimiento.",
    curiosidad: "Originalmente las zanahorias no eran naranjas, sino moradas o amarillas, y el color actual fue desarrollado con el tiempo.",
    tags:["huerta", "nutritiva"],
  },
  {
    id:10,
    nombre: "Papa",
    cientifico:"Solanum tuberosum",
    emoji:"🥔 ",
    categoria:"huerta",
    diasRiego:3,
    luz: "Sol directo",
    mesesSiembra:"Agosto a Noviembre",
    dificultad:"Media",
    descripcion: " Planta que produce tubérculos subterráneos ampliamente consumidos en todo el mundo. Es un alimento muy importante por su valor energético y versatilidad en la cocina. Crece bajo tierra mientras la planta se desarrolla en superficie.",
    cuidados: " Es fundamental ir cubriendo con tierra la base de la planta a medida que crece. Necesita suelos bien aireados y evitar el exceso de agua. También se debe cuidar de plagas.",
    curiosidad: " La papa fue uno de los alimentos clave que ayudó al crecimiento de la población mundial por su alto rendimiento y facilidad de cultivo.",
    tags:["huerta", "sol"],
  },
   {
    id:11,
    nombre: "Rúcula",
    cientifico:"Eruca vesicaria",
    emoji:"🌿",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol directo o semisombra",
    mesesSiembra:"Todo el año",
    dificultad:"Fácil",
    descripcion: " Planta de hojas verdes alargadas con un sabor fuerte, picante y ligeramente amargo. Es muy utilizada en ensaladas, pizzas y platos modernos. Crece rápidamente y es ideal para quienes recién comienzan con la huerta.",
    cuidados: " Se recomienda cosechar las hojas jóvenes para obtener mejor sabor y textura. Necesita riego moderado y suelos bien drenados. Puede rebrotar varias veces si se corta correctamente.",
    curiosidad: "La rúcula crece tan rápido que en pocas semanas ya puede estar lista para consumir, lo que la hace muy práctica.",
    tags:["huerta", "rápida"],
  },
  {
    id:12,
    nombre: "Berenjena",
    cientifico:" Solanum melongena",
    emoji:"🍆 ",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol directo",
    mesesSiembra:"Primavera",
    dificultad:"Media",
    descripcion: "  Planta que produce frutos de color violeta oscuro con pulpa suave y esponjosa. Se utiliza en muchas recetas como al horno, frita o en guisos. Requiere calor y tiempo para desarrollarse correctamente.",
    cuidados: " Necesita temperaturas cálidas constantes y buena exposición solar. Es importante mantener un riego regular sin encharcar el suelo. También conviene protegerla de plagas y vientos fuertes.",
    curiosidad: " La berenjena pertenece a la misma familia que el tomate y la papa, conocidas como solanáceas.",
    tags:["huerta", "suave"],
  },
  {
    id:13,
    nombre: "Cebolla",
    cientifico:"Allium cepa",
    emoji:"🧅  ",
    categoria:"huerta",
    diasRiego:3,
    luz: "Sol directo",
    mesesSiembra:"Otoño e invierno",
    dificultad:"Fácil",
    descripcion: "Planta que forma un bulbo subterráneo muy utilizado en la cocina por su sabor intenso. Puede consumirse cruda o cocida, cambiando su sabor según la preparación. Es un cultivo muy común y adaptable. ",
    cuidados: " Necesita suelos bien drenados y riegos moderados para evitar que el bulbo se pudra. Es importante mantener el área libre de malezas. No requiere demasiados cuidados, por lo que es ideal para principiantes.",
    curiosidad: "Al cortar cebolla se libera un gas que irrita los ojos, lo que provoca el lagrimeo característico.",
    tags:["huerta", "fácil"],
  },
{ 
   id:14,
    nombre: "Frutilla",
    cientifico:"Fragaria",
    emoji:"🍓  ",
    categoria:"huerta",
    diasRiego:2,
    luz: "Sol o semisombra",
    mesesSiembra:"Otoño y primavera",
    dificultad:"Media",
    descripcion: "Planta pequeña que produce frutos rojos dulces y jugosos. Es muy utilizada en postres, jugos y para consumir fresca. Puede cultivarse tanto en tierra como en macetas.",
    cuidados: "Necesita suelo bien drenado y riego regular sin encharcar. Conviene proteger los frutos del contacto directo con la tierra y de plagas.",
    curiosidad: "Lo que parece la “fruta” en realidad no lo es completamente; las semillas de afuera son los verdaderos frutos.",
    tags:["huerta", "fruta"],
},
  // ─── FLORES ───────────────────────────────────────
{
   id:15,
   nombre:"Lavanda",
   cientifico:"Lavandula angustifolia",
   emoji:"🪻",
   categoria:["flores", "Aromáticas"],
   diasRiego:5,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Fácil",
   descripcion:"Arbusto aromático con hojas finas grisáceas y flores violetas agrupadas en espigas. Valorado por su aroma intenso y relajante, además de su aspecto decorativo en jardines.",
   cuidados:"Necesita suelos secos y bien drenados, ya que no tolera el exceso de agua. Es importante ubicarla en lugares soleados y podarla después de la floración para que crezca más compacta.",
   curiosidad:"En la antigüedad, los romanos la usaban para perfumar sus baños (de ahí viene el nombre “lavanda”, de lavare = lavar).",
   tags:["flores", "aromática"],
},

{
   id:16,
   nombre:"Rosa",
   cientifico:"Rosa spp",
   emoji:"🌹",
   categoria:"flores",
   diasRiego:2,
   luz:"Sol directo",
   mesesSiembra:"Otoño o primavera",
   dificultad:"Media",
   descripcion:"Arbusto ornamental con tallos espinosos y flores grandes, vistosa y de variados colores. Es una de las plantas más populares por su belleza y su valor simbólico.",
   cuidados:"Requiere riego frecuente sin encharcar, buena exposición al sol y podas regulares para estimular la floración. También es importante controlar plagas como pulgones u hongos.",
   curiosidad:"La rosa más antigua conocida tiene más de 1.000 años y sigue floreciendo en Alemania.",
   tags:["flores", "belleza"],
},

{
   id:17,
   nombre:"Jazmín",
   cientifico:"Jazminum officinale",
   emoji:"🌼",
   categoria: ["flores", "Aromáticas"],
   diasRiego:3,
   luz:"Sol o semisombra",
   mesesSiembra:"Primavera",
   dificultad:"Media",
   descripcion:"Planta arbustiva con flores blancas pequeñas muy perfumadas. Se utiliza mucho para decorar jardines, muros o balcones.",
   cuidados:"Necesita un soporte para trepar, riego regular y un suelo fértil. Es importante posarlo para controlar su crecimiento y estimular nuevas flores.",
   curiosidad:"Su perfume es más intenso de noche porque atrae insectos nocturnos para polinizarse.",
   tags:["flores", "aromática"],
},

{
   id:18,
   nombre:"Geranio",
   cientifico:"Pelargonium spp",
   emoji:"🌺",
   categoria:"flores",
   diasRiego:3,
   luz:"Sol o semisombra",
   mesesSiembra:"Primavera",
   dificultad:"Fácil",
   descripcion:"El geranio es una planta muy resistente con hojas redondeadas y flores agrupadas en tonos rojos, rosas, blancos o violetas. Es ideal para macetas y balcones.",
   cuidados:"Requiere riego moderado y buen drenaje. Es importante retirar las flores secas para favorecer nuevas floraciones y evitar plagas.",
   curiosidad:"Algunas variedades tienen olor a limón, menta o incluso a rosa.",
   tags:["flores", "colores"],
},

{
   id:19,
   nombre:"Campanilla",
   cientifico:"Campanula spp",
   emoji:"🌸",
   categoria:"flores",
   diasRiego:2,
   luz:"Sol o semisombra",
   mesesSiembra:"Primavera",
   dificultad:"Fácil",
   descripcion:"Planta herbácea con flores en forma de campana, generalmente de color azul, violeta o blanco. Se utiliza mucho en jardines por su delicadeza.",
   cuidados:"Necesita suelos húmedos pero bien drenados y riego regular. Se adapta tanto al sol como a la semisombra, pero hay que protegerla del calor extremo.",
   curiosidad:"En algunas culturas se creía que atraían hadas por su forma de campana.",
   tags:["flores", "fácil"],
},

{
   id:20,
   nombre:"Alegría del hogar",
   cientifico:"Impatiens walleriana",
   emoji:"🌺",
   categoria:["flores", "interior"],
   diasRiego:2,
   luz:"Semisombra",
   mesesSiembra:"Primavera o verano",
   dificultad:"Fácil",
   descripcion:"Planta pequeña y muy colorida, con flores en tonos rosados, rojos, blancos o naranjas. Es muy usada para decorar interiores o lugares con poca luz.",
   cuidados:"Necesita húmedad constante y no tolera el sol directo, ya que puede quemar sus hojas. Es importante mantener el suelo húmedo pero sin encharcar.",
   curiosidad:"Sus semillas “explotan” cuando las tocás, por eso también se llama “impatiens”.",
   tags:["flores", "interior"],
},

{
   id:21,
   nombre:"Caléndula",
   cientifico:"Calendula officinalis",
   emoji:"🏵️",
   categoria:"flores",
   diasRiego:2,
   luz:"Sol directo",
   mesesSiembra:"Otoño o primavera",
   dificultad:"Fácil",
   descripcion:"Planta herbácea con flores llamativas de color amarillo o naranja intenso. Es muy valorada tanto por su belleza como por sus propiedades medicinales.",
   cuidados:"Es resistente y fácil de cultivar, necesita sol directo y riego moderado. Se recomienda quitar las flores marchitas para prolongar la floración.",
   curiosidad:"Se usa en cremas y remedios naturales para la piel, ya que tiene propiedades cicatrizantes y antiinflamatorias.",
   tags:["flores", "medicinal"],
},
{
   id:22,
   nombre:"Tulipán",
   cientifico:"Tulipa",
   emoji:"🌷",
   categoria:"flores",
   diasRiego:2,
   luz:"Sol directo o semisombra",
   mesesSiembra:"Otoño",
   dificultad:"Media",
   descripcion:"El tulipán es una planta ornamental muy conocida por sus flores grandes y coloridas, que pueden ser rojas, amarillas, rosas o violetas. Crece a partir de un bulbo y es muy utilizada en jardines y macetas para decoración.",
   cuidados:"Plantá los bulbos en otoño en un suelo bien drenado. Evitá el exceso de agua porque puede pudrir el bulbo.",
   curiosidad:"Los tulipanes fueron tan valiosos en el siglo XVII que en Países Bajos llegaron a costar más que una casa.",
   tags:["flores", "colores"],
},
  // ─── SUCULENTAS ───────────────────────────────────────

{
   id:23,
   nombre:"Echeveria",
   cientifico:"Echeveria elegans",
   emoji:"🪴",
   categoria:"suculentas",
   diasRiego:7,
   luz:"Sol directo",
   mesesSiembra:"Primavera o verano",
   dificultad:"Fácil",
   descripcion:"Suculenta que forma una roseta perfecta, parecida a una flor. Sus hojas son carnosas, suaves al tacto y pueden tener tonos verdes, rosados o azulados, dependiendo de la especie y la luz. Es muy decorativa en macetas.",
   cuidados:"Necesita un sustrato bien drenado (tipo arena o tierra para cactus), evitar que el agua quede acumulada en el centro de la roseta y regar solo cuando la tierra esté completamente seca.",
   curiosidad:" Puede cambiar de color según la cantidad de sol que recibe, volviéndose más rosada o intensa.",
   tags:["suculentas", "sol"],
},

{
   id:24,
   nombre:"Aloe Vera",
   cientifico:"Aloe vera",
   emoji:"🌿",
   categoria:"suculentas",
   diasRiego:10,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Fácil",
   descripcion:"Planta suculenta de hojas largas, gruesas y puntiagudas con pequeños dientes en los bordes. En su interior contiene un gel transparente muy conocido por sus propiedades medicinales.",
   cuidados:"Requiere poco riego y mucha luz. Es importante usar macetas con buen drenaje y evitar el frío extremo. No tolera el exceso de agua, ya que puede pudrir sus raíces.",
   curiosidad:"Puede sobrevivir varias semanas sin agua gracias al gel que almacena.",
   tags:["suculentas", "medicinal"],
},

{
   id:25,
   nombre:"Haworthia",
   cientifico:"Haworthia fasciata",
   emoji:"🪴",
   categoria:["suculentas", "interior"],
   diasRiego:10,
   luz:"Luz indirecta",
   mesesSiembra:"Primavera o verano",
   dificultad:"Fácil",
   descripcion:"Suculenta pequeña que forma una roseta compacta con hojas triangulares, verdes oscuras y con bandas blancas. Su tamaño la hace ideal para escritorios o espacios pequeños.",
   cuidados:"Prefiere luz indirecta, ya que el sol fuerte puede quemar sus hojas. Regar solo cuando el sustrato esté seco y evitar el exceso de humedad.",
   curiosidad:"Es apodada “planta cebra” por sus rayas blancas tan marcadas.",
   tags:["suculentas", "pequeña"],
},

{
   id:26,
   nombre:"Piedra lunar",
   cientifico:"Pachyphytum oviferum",
   emoji:"🪴",
   categoria:"suculentas",
   diasRiego:12,
   luz:"Semisombra",
   mesesSiembra:"Primavera",
   dificultad:"Fácil",
   descripcion:"Es una suculenta muy decorativa con hojas gruesas, redondeadas y de tonos suaves entre gris, verde y rosado. Tiene un aspecto delicado y compacto, ideal para macetas pequeñas y ambientes luminosos.",
   cuidados:"Regá solo cuando la tierra esté completamente seca y evitá tocar mucho sus hojas, ya que tienen una capa protectora que puede dañarse fácilmente.",
   curiosidad:"Sus hojas tienen una especie de “polvito” natural que le da ese aspecto mate, y sirve como protección contra el sol y la deshidratación.",
   tags:["suculentas", "decorativa"],


},

{
   id:35,
   nombre:"Jade",
   cientifico:"Crassula ovata",
   emoji:"🌿",
   categoria:"suculentas",
   diasRiego:10,
   luz:"Mucha luz o sol",
   mesesSiembra:"Primavera o verano",
   dificultad:"Fácil",
   descripcion:"Suculenta de hojas gruesas y brillantes que crece como un pequeño arbusto, pudiendo formar un tronco leñoso con el tiempo. Es muy decorativa y puede llegar a parecer un arbolito mini.",
   cuidados: "Necesita mucha luz y riego moderado, dejando secar la tierra entre riegos. Es clave usar buen drenaje y evitar el exceso de agua para que no se pudran las raíces.",
   curiosidad:"En algunas culturas se regala para atraer dinero y prosperidad",
   tags:["suculentas", "decorativa"],

},


{
   id:36,
   nombre:"Lengua de suegra",
   cientifico:"Dracaena trifasciata",
   emoji:"🌿",
   categoria:"suculentas",
   diasRiego:10,
   luz:"Sol, luz o sombra",
   mesesSiembra:"Primavera o verano",
   dificultad:"Muy fácil",
   descripcion:"Planta de hojas largas, rígidas y verticales, muy resistente y adaptable. Es ideal para interiores y aporta un toque moderno a cualquier espacio.",
   cuidados: "Requiere poco riego y soporta tanto poca luz como ambientes luminosos. Lo más importante es no regarla en exceso y usar una maceta con buen drenaje.",
   curiosidad:"Es de pocas plantas que liberan oxígeno incluso de noche.",
   tags:["suculentas", "decorativa"],

},

// ─── ÁRBOLES ───────────────────────────────────────
{
   id:27,
   nombre:"Limonero",
   cientifico:"Citrus limon",
   emoji:"🍋",
   categoria:["árboles", "huerta"],
   diasRiego:4,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Media",
   descripcion:"Árbol frutal muy popular que produce limones ácidos y aromáticos, utilizados en cocina, bebidas y limpieza. Puede cultivarse en jardines o en macetas grandes, y mantiene hojas verdes durante todo el año.",
   cuidados:"Necesita mucho sol y un suelo bien drenado para evitar enfermedades en las raíces. En invierno conviene protegerlo de las heladas, ya que el frío intenso puede dañarlo.",
   curiosidad:"El limonero puede florecer varias veces al año en climas cálidos, produciendo frutos en distintas etapas. Además, sus flores blancas tienen un aroma muy agradable y característico.",
   tags:["árboles", "fruta"],
},
{
   id:28,
   nombre:"Naranjo",
   cientifico:"Citrus sinensis",
   emoji:"🍊",
   categoria:["árboles", "huerta"],
   diasRiego:3,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Media",
   descripcion:"Árbol frutal que produce naranjas dulces y jugosas, muy consumidas en todo el mundo. Es ideal para jardines y necesita espacio para desarrollarse correctamente.",
   cuidados:"Requiere riego regular pero sin encharcar el suelo, ya que el exceso de agua puede afectar sus raíces. Es importante ubicarlo en un lugar con mucho sol para lograr una buena producción de frutos.",
   curiosidad:"Un naranjo adulto puede producir cientos de naranjas en una sola temporada. Además, es un árbol que puede vivir hasta 50 años si se cuida correctamente.",
   tags:["árboles", "fruta"],
},
{
   id:29,
   nombre:"Manzano",
   cientifico:"Malus domestica",
   emoji:"🍎",
   categoria: ["árboles", "huerta"],
   diasRiego:4,
   luz:"Sol directo",
   mesesSiembra:"Invierno",
   dificultad:"Media",
   descripcion:"Árbol frutal muy conocido que produce manzanas de diferentes colores como rojo, verde o amarillo. Se adapta mejor a climas templados y es común en huertas y grandes cultivos.",
   cuidados:"Necesita poda regular para crecer fuerte y producir frutos de mejor calidad. También se recomienda sembrar en invierno para desarrollarse correctamente.",
   curiosidad:"Existen más de 7.000 variedades de manzanas en todo el mundo. Cada una tiene distinto sabor, textura y uso en la cocina.",
   tags:["árboles", "fruta"],
},
{
   id:30,
   nombre:"Quinotero",
   cientifico:"Citrus japonica",
   emoji:"🍊",
   categoria: ["árboles", "huerta"],
   diasRiego:3,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Media",
   descripcion:"Árbol pequeño que produce quinotos, frutos similares a pequeñas naranjas, muy llamativos y decorativos. Es ideal para macetas o espacios reducidos, ya que no crece demasiado.",
   cuidados:"Necesita buena luz solar y riego moderado, evitando el exceso de agua. Se adapta bien a macetas, pero es importante usar tierra con buen drenaje.",
   curiosidad:"A diferencia de otros cítricos, el fruto del quinoto se come entero, incluida la cáscara. La cáscara es dulce, mientras que el interior es más ácido, generando un sabor único.",
   tags:["árboles", "fruto"],
},
{
   id:31,
   nombre:"Palto",
   cientifico:"Persea americana",
   emoji:"🥑",
   categoria:"árboles",
   diasRiego:5,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Difícil",
   descripcion:"Árbol tropical que produce paltas, un fruto muy nutritivo y popular en la alimentación actual. Puede crecer bastante y necesita espacio, por lo que no siempre es ideal para lugares pequeños.",
   cuidados:"Requiere clima cálido, buena exposición al sol y suelo bien drenado para evitar problemas.",
   curiosidad:"Un árbol de palta puede tardar entre 3 y 13 años en producir sus primeros frutos. Además, algunas variedades necesitan otro árbol cercano para poder polinizar correctamente.",
   tags:["árboles", "fruto"],
},
{
   id:32,
   nombre:"Pino",
   cientifico:"Pinus spp",
   emoji:"🌲",
   categoria:"árboles",
   diasRiego:7,
   luz:"Sol directo",
   mesesSiembra:"Otoño o primavera",
   dificultad:"Fácil",
   descripcion:"El pino es un árbol que mantiene sus hojas durante todo el año y puede crecer mucho en altura. Es muy común en bosques y también en jardines grandes, donde se utiliza por su valor ornamental y su resistencia.",
   cuidados:"Cuando es joven necesita riego moderado, pero una vez establecido puede resistir sequías sin problemas. Es importante plantarlo en espacios amplios, ya que sus raíces y tamaño pueden crecer bastante.",
   curiosidad:"Los pinos producen piñas donde se encuentran sus semillas, algunas comestibles como los piñones. Además, existen más de 100 especies de pinos distribuidas en distintas partes del mundo.",
   tags:["árboles", "grande"],
},
{
   id:33,
   nombre:"Palo borracho",
   cientifico:"Ceiba speciosa",
   emoji:"🌳",
   categoria:"árboles",
   diasRiego:6,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Media",
   descripcion:"El palo borracho es un árbol ornamental muy llamativo por su tronco grueso y abultado, que almacena agua. Sus flores grandes y rosadas lo hacen muy atractivo en primavera, siendo común en calles y plazas.",
   cuidados:"Necesita espacio para crecer y buena exposición al sol para desarrollarse correctamente. Cuando es joven requiere riego moderado, pero de adulto resiste bien la sequía.",
   curiosidad:"Su nombre viene de la forma “hinchada” del tronco, que parece una botella o un cuerpo “borracho”. Además, el tronco tiene espinas que lo protegen de animales.",
   tags:["árboles", "grande"],
},
{
   id:34,
   nombre:"Ceibo",
   cientifico:"Erythrina crista-galli",
   emoji:"🌺",
   categoria:["árboles", "flores"],
   diasRiego:4,
   luz:"Sol directo",
   mesesSiembra:"Primavera",
   dificultad:"Media",
   descripcion:"El ceibo es un árbol pequeño o mediano conocido por sus flores rojas intensas y muy llamativas. Es muy común en zonas húmedas y a orillas de ríos, donde crece naturalmente.",
   cuidados:"Prefiere suelos húmedos y buen acceso al sol, por lo que es ideal para exteriores. No tolera bien las heladas fuertes, por lo que conviene protegerlo en climas fríos.",
   curiosidad:"El ceibo es la flor nacional de la Argentina y está muy presente en la cultura popular. Existe una tradición artesanal en Argentina y Uruguay donde se hacen “patitos” doblando sus flores rojas, algo muy común entre niños y relacionado con la leyenda de Anahí.",
   tags:["árboles", "flores"],
},

// ─── CACTUS ───────────────────────────────────────
{
   id: 37,
   nombre: "Cactus Erizo", 
   cientifico: "Echinocactus Grusonii" ,
   emoji: "🌵" ,
   categoria: "cactus",
   diasRiego:20,
   luz: "Sol directo",
   mesesSiembra: "Primavera o verano",
   dificultad: "Fácil" ,
   descripcion:"Es un cactus de forma redonda y muy simétrica, cubierto de espinas amarillas que lo hace destacar mucho visualmente. Es muy usado como planta en jardines y macetas grandes.",
   cuidados: "Necesita un sustrato con excelente drenaje para evitar que se acumule agua en las raíces. El riego debe ser moderado dejando secar la tierra entre riegos.",
   curiosidad: "Puede vivir durante décadas si se cuida bien. Con el tiempo puede alcanzar tamaños grandes y además es uno de los cactus más resistentes y longevos de la historia.",
   tags: ["cactus", "resistente"] ,
} ,
{
   id: 38,
   nombre: "Cactus Navideño", 
   cientifico: "Schlumbergera Truncata" ,
   emoji: "🌵" ,
   categoria: ["cactus", "flores"],
   diasRiego:10,
   luz: "Sol indirecto",
   mesesSiembra: "Primavera",
   dificultad: "Fácil" ,
   descripcion:"El cactus navideño es una planta muy popular por sus flores coloridas que aparecen durante el invierno, especialmente entre mayo y julio. A diferencia de otros cactus del desierto, tiene tallos planos y colgantes, y prefiere ambientes frescos y húmedos con luz indirecta.",
   cuidados: "Necesita riego moderado, manteniendo la tierra apenas húmeda durante el invierno y reduciendo el riego en épocas más frías. Conviene ubicarlo cerca de una ventana luminosa pero sin sol directo fuerte, especialmente en verano.",
   curiosidad: "Aunque se llama “cactus”, esta planta proviene de selvas tropicales de Sudamérica y no de zonas desérticas. En Argentina muchas personas la usan como planta decorativa de invierno porque florece cuando la mayoría de las plantas tienen menos flores.",
   tags: ["cactus", "flores"] ,

},
{
   id: 39,
   nombre: "Opuntia",
   cientifico: "Opuntia ficus-indica",
   emoji: "🌵",
   categoria: "cactus",
   diasRiego: 20,
   luz: "Sol directo" ,
   mesesSiembra:"Primavera o verano",
   dificultad: "Fácil",
   descripcion: "Este cactus tiene forma de paletas planas que crecen unas sobre otras. Es muy resistente a condiciones extremas como el calor y la sequía. Puede crecer bastante y formar grandes estructuras con el tiempo.",
   cuidados: "Necesita pleno sol para desarrollarse correctamente y crecer fuerte. El riego debe ser escaso, ya que tolera muy bien la falta de agua. Es muy importante darle espacio para que pueda expandirse rápidamente.",
   curiosidad: "Produce frutos llamados tunas que son comestibles y dulces. Es uno de los cactus más conocidos del mundo.",
   tags: ["cactus", "resistente"]
},
{
   id: 40,
   nombre: "Cactus Columna",
   cientifico: "Cereus peruvianus",
   emoji: "🌵",
   categoria: ["cactus", "flores"],
   diasRiego: 15,
   luz: "Sol directo",
   mesesSiembra: "Primavera o verano",
   dificultad: "Fácil",
   descripcion: "Es un cactus alto y vertical que puede alcanzar varios metros de altura. Tiene un crecimiento rápido en comparación con otros cactus. Se utiliza mucho en jardines por su forma imponente.",
   cuidados: "Requiere sol directo durante gran parte del día para crecer correctamente. El riego debe ser moderado, evitando siempre el encharcamiento. Necesita un suelo bien drenado para evitar problemas en las raíces.",
   curiosidad: "Sus flores son grandes y muy llamativas, se abren únicamente por la noche. Son consideradas especiales por su corta duración",
   tags: ["cactus", "flores"] ,
},
{
   id: 41,
   nombre: "Mammillaria",
   cientifico: "Mammillaria spp",
   emoji: "🌵",
   categoria: ["cactus", "interior", "flores"],
   diasRiego: 12,
   luz: "Sol directo",
   mesesSiembra: "Primavera o verano",
   dificultad:"Fácil",
   descripcion: "Es un cactus pequeño y redondo, ideal para macetas y espacios pequeños. Posee espinas finas y una forma muy decorativa. Además suele producir flores que forman una corona en la parte superior.",
   cuidados: "Necesita una buena iluminación, preferentemente mucha luz natural. El riego debe ser moderado y siempre con buen drenaje, es importante no excederse con el agua para evitar que se pudra.",
   curiosidad: "Sus flores forman una especie de aro alrededor del cactus. Es muy elegido por principiantes y existen muchas variedades con formas distintas.",
   tags:  ["cactus", "flores"] ,
},
{
   id: 42,
   nombre:  "Cactus cola de mono",
   cientifico: "Cleistocactus colademononis",
   emoji: "🌵",
   categoria: "cactus",
   diasRiego: 15,
   luz: "Sol suave",
   mesesSiembra: "Primavera o verano",
   dificultad: "Fácil",
   descripcion: "Es un cactus colgante con tallos largos y delgados cubierto de pelitos blancos que le dan un aspecto suave. Sus ramas crecen bastante y caen como si fuesen colas, lo que lo hace muy decorativo. También produce flores de color rojo intenso que contrastan con su apariencia.",
   cuidados: "Necesita un lugar con mucha luz pero evitando el sol directo que puede dañarlo. Es importante usar macetas colgantes y asegurar un buen drenaje." ,
   curiosidad: "Su nombre viene porque parece la cola de un mono. Los pelitos ayudan a protegerlo del sol intenso y además es muy usado como planta decorativa. ",
   tags: ["cactus", "decorativo"],
},
]